config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: :destroy
  end

  resources :bookmarks, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks

  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: :destroy

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = @bookmark.list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show]

  def index
    @lists = List.all
  end

  def show
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(list)
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end

  def set_list
    @list = List.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/bookmarks/new.html.erb
<h1 class="text-center">New Bookmark</h1>
<div>
  <%= simple_form_for [@bookmark] do |f| %>
    <%= f.input :comment %>
    <%= f.association :list %>
    <%= f.association :movie %>
    <%= f.button :submit, class: "btn btn-flat btn-block" %>
    <%= link_to "Back to list", lists_path, class: "btn btn-flat btn-block" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="cards-container">
  <h2 class="text-center mb-4">Categories</h2>
  <div class="cards">
    <% @lists.each do |list| %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
        <%= link_to list.name, list_path(list), class: "list" %>
      </div>
    <% end %>
  </div>
  <br>
  <%= link_to "Add To List", new_list_path, class: "btn btn-ghost" %>
</div>

app/views/lists/new.html.erb
<%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>
<br>
<%= link_to "Back to list", lists_path %>

app/views/lists/show.html.erb
<div class="cards-container">
  <h2 class="text-center mb-4"><%= @list.name %></h2>
  <div class="cards">
    <% @list.movies.each do |movie| %>
      <div class="movie">
        <img alt=<%= movie.title %> width="200" src=<%= movie.poster_url %> class="card-category" />
        <p><%= movie.title %></p>
        <%# <% bookmark = List.find(params[:id]) %>
        <% bookmark = Bookmark.find_by(list: @list, movie: movie) %>
        <%= link_to "Remove", list_bookmark_path(bookmark), bookmark_id: @bookmark, method: :delete, data: { confirm: "Are you sure?" } %>
      </div>
    <% end %>
  </div>
  <br>
  <%= link_to "Back to list", lists_path, class: "btn btn-ghost" %>
</div>

app/views/pages/home.html.erb
<div class="background">
</div>

app/views/shared/_navbar.html.erb
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag(asset_path('logo.png')) %>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
          <%# <img class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://kitt.lewagon.com/placeholder/users/ssaunier" /> %>
          <span class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Watchlist</span>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "View List", lists_path, class: "dropdown-item" %>
            <%= link_to "New Bookmark", new_bookmark_path, class: "dropdown-item" %>
          </div>
        </li>
      </ul>
    </div>
  </div>